config/routes.rb
Rails.application.routes.draw do
  root 'top_pages#top'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'

  resources :musics do
    collection do
      get 'search'
    end    
  end
  
  resources :dances do
    collection do
      get 'search'
    end
  end
  
  resources :stages do
    collection do
      get 'search'
    end      
  end
  
  resources :artists
  
  resources :tags do
    get 'musics',    to: 'musics#tag'
    get 'dances',    to: 'dances#tag'
    get 'stages',    to: 'stages#tag'
  end
  
  resources :lists do
    get 'musics',    to: 'musics#list'
    get 'dances',    to: 'dances#list'
    get 'stages',    to: 'stages#list'
  end

  resources :comments, only: [:create, :destroy]
end

app/models/dance.rb
class Dance < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true, length: { maximum: 100 }
  validates :info, length: { maximum: 200 }
  validates :youtube_url, presence: true
  before_save :shape_off
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :list_maps, dependent: :destroy
  has_many :lists, through: :list_maps
  has_many :comments, dependent: :destroy

  def shape_off
    self.youtube_url = youtube_url.last(11)
  end

  def feed_comment(dance_id)
    Comment.where("dance_id = ?", dance_id)
  end
end

app/controllers/dances_controller.rb
class DancesController < ApplicationController
  before_action :logged_in_user, except: [:show, :tag, :list, :search]

  def new
    @dance = Dance.new
  end

  def show
    @dance = Dance.find(params[:id])
    @dance_tags = @dance.tags
    @dance_lists = @dance.lists
    @comment = Comment.new
  end

  def search
    @results = @q_dance.result
  end

  def tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @dances = @tag.dances.all
  end

  def list
    @list_all = List.all
    @list = List.find(params[:list_id])
    @dances = @list.dances.all
  end

  def create
    @dance = Dance.new(dance_params)
    tag_list = params[:dance][:tag_name].split(',')
    list_all = params[:dance][:list_name].split(',')
    if @dance.save
      @dance.save_tag(tag_list)
      @dance.save_list(list_all)
      flash[:success] = "新しいdanceが登録されました"
      redirect_to @dance
    else
      render 'dances/new'
    end
  end

  def edit
    @dance = Dance.find(params[:id])
    @tag_list = @dance.tags.pluck(:tag_name).join(',')
    @list_all = @dance.lists.pluck(:list_name).join(',')
  end

  def update
    @dance = Dance.find(params[:id])
    tag_list = params[:dance][:tag_name].split(',')
    list_all = params[:dance][:list_name].split(',')
    if @dance.update_attributes(dance_params)
      @dance.save_tag(tag_list)
      @dance.save_list(list_all)
      flash[:success] = "更新されました"
      redirect_to @dance
    else
      flash[:danger] = "エラーがあります"
      render @dance
    end
  end

  def destroy
    @dance = Dance.find(params[:id])
    if logged_in?
      @dance.destroy
      flash[:success] = "削除されました"
      redirect_to root_url
    else
      flash[:danger] = "管理人しか削除できません"
      redirect_to @dance
    end
  end

  private

    def dance_params
      params.require(:dance).permit(:name, :info, :date, :youtube_url)
    end
end

app/helpers/dances_helper.rb
module DancesHelper
end

app/views/dances/_dance_form.html.erb
<%= form_with model: @dance, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class = 'form-group'>
    <%= f.label :name %>  <span class="input-need">※must</span>
    <%= f.text_field :name, class: 'form-control', id: 'dance_name' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :info %>
    <%= f.text_field :info, size: "60x4", class: 'form-control', id: 'dance_info' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :date %>
    <%= f.date_select :date, class: 'form-control', id: 'dance_date' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :youtube_url %>  <span class="input-need">※must</span>
    <%= f.text_field :youtube_url, class: 'form-control', id: 'dance_youtube_url' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :tag %>
    <%= f.text_field :tag_name,
                     placeholder: "タグを複数つけるには' , 'で区切ってください", 
                     class: 'form-control' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :list %>
    <%= f.text_field :list_name,
                     placeholder: "複数のリストに入れるには' , 'で区切ってください", 
                     class: 'form-control' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/dances/edit.html.erb
<% provide(:title, "Edit_dance") %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
     <%= form_with model: @dance, local: true do |f| %>
       <%= render 'shared/error_messages', object: f.object %>
       <div class = 'form-group'>
         <%= f.label :name %>　<span class="input-need">※must</span>
         <%= f.text_field :name, class: 'form-control', id: 'dance_name' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :info %>
         <%= f.text_field :info, size: "60x4", class: 'form-control', id: 'dance_info' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :date %>
         <%= f.date_select :date, class: 'form-control', id: 'dance_date' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :youtube_url %>  <span class="input-need">※must</span>
         <%= f.text_field :youtube_url, class: 'form-control', id: 'dance_youtube_url' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :tag %>
         <%= f.text_field :tag_name,
                          value: @tag_list,
                          placeholder: "タグを複数つけるには' , 'で区切ってください", 
                          class: 'form-control' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :list %>
         <%= f.text_field :list_name,
                          value: @list_all,
                          placeholder: "複数のリストに入れるには' , 'で区切ってください", 
                          class: 'form-control' %>
       </div>
       <%= f.submit "更新する", class: 'btn btn-primary' %>
       <%= link_to "削除する", dance_path(@dance), method: :delete,
                               data: { confirm: "本当に削除してよろしいですか？" } %>
     <% end %>
    </div>
  </div>
</div>

app/views/dances/new.html.erb
<% provide(:title, "New_dance") %>
<div class="container">
  <h1>New_dance</h1>
  <div class="row">
    <div class="col-md-12">
      <%= render 'dances/dance_form' %>
    </div>
  </div>
</div>

app/views/dances/search.html.erb
<%= render "/layouts/search" %>

app/views/dances/show.html.erb
<% provide(:title, "#{@dance.name}") %>
<% @comments = @dance.feed_comment(@dance.id) %>
<div class="container">
  <div class="row">
    <div class="col-12">
        <iframe width="100%" height="500px" src="https://www.youtube.com/embed/<%= @dance.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="col-12 edit-button">
      <div class="change-dance">
        <% if logged_in? %>
          <%= link_to "編集", edit_dance_path(@dance), class: 'edit-dance' %>　
        <% end %>
      </div>
    </div>
    <div class="col-12 contents-info">
      <h2 class="contents-name"><%= @dance.name %></h2>
      <h4><%= @dance.info %></h4>
      <div class="contents-date">
        <h5>動画投稿日：<%= @dance.date %></h5>
      </div>
      <p>
        #Tag: 
        <% @dance_tags.each do |tag| %>
          <%= link_to tag.tag_name, tag_dances_path(tag_id: tag.id) %>
        <% end %>
      </p>
      <p>
        #List: 
        <% @dance_lists.each do |list| %>
          <%= link_to list.list_name, "../lists/#{list.id}" %>
        <% end %>
      </p>
    </div>
    <div class="col-12 comment">
      <%= render "comments/feed_comments" %>
      <%= render "comments/new" %>
    </div>
    <div class="relate_contents">
      <% @dance_tags.each do |dance_tag| %>
        <% dance_tag.dances.each do |relate_dance| %>
          <% unless relate_dance === @dance %>
            <div class="relate_image">
              <%= link_to image_tag("http://img.youtube.com/vi/#{relate_dance.youtube_url}/mqdefault.jpg", class: "contents_image"), relate_dance %>
              <%= link_to relate_dance.name, relate_dance, class: "result_name" %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/dances/tag.html.erb
<% provide(:title, "search") %>
<div class="container">
  <p>
    <%= "タグが - #{@tag.tag_name} - のdance一覧" %>
  </p>
  <div class="row search_result">
      <% @dances.each do |dance| %>
      <div class="search_image">
        <%= link_to image_tag("http://img.youtube.com/vi/#{dance.youtube_url}/hqdefault.jpg", class: "contents_image"), dance %>
        <%= link_to dance.name, dance, class: "result_name" %>
      </div>
      <% end %>
  </div>
</div>