config/routes.rb
Rails.application.routes.draw do
  root 'top_pages#top'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'

  resources :musics do
    collection do
      get 'search'
    end    
  end
  
  resources :dances do
    collection do
      get 'search'
    end
  end
  
  resources :stages do
    collection do
      get 'search'
    end      
  end
  
  resources :artists
  
  resources :tags do
    get 'musics',    to: 'musics#tag'
    get 'dances',    to: 'dances#tag'
    get 'stages',    to: 'stages#tag'
  end
  
  resources :lists do
    get 'musics',    to: 'musics#list'
    get 'dances',    to: 'dances#list'
    get 'stages',    to: 'stages#list'
  end

  resources :comments, only: [:create, :destroy]
end

app/models/stage.rb
class Stage < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :info, length: { maximum: 500 }
  has_many_attached :images
  has_many :stage_artists, dependent: :destroy
  has_many :artists, through: :stage_artists
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :list_maps, dependent: :destroy
  has_many :lists, through: :list_maps
  has_many :comments, dependent: :destroy

  def feed_comment(stage_id)
    Comment.where("stage_id = ?", stage_id)
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :logged_in_user, except: [:show, :tag, :list, :search]

  def new
    @stage = Stage.new
    @artist = @stage.artists.build
  end

  def show
    @stage = Stage.find(params[:id])
    @stage_tags = @stage.tags
    @stage_lists = @stage.lists
    @comment = Comment.new
  end

  def search
    @results = @q_stage.result
  end

  def tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @stages = @tag.stages.all
  end

  def list
    @list_all = List.all
    @list = List.find(params[:list_id])
    @stages = @list.stages.all
  end

  def create
    @stage = Stage.new(stage_params)
    tag_list = params[:stage][:tag_name].split(',')
    list_all = params[:stage][:list_name].split(',')
    if @stage.save
      @stage.save_tag(tag_list)
      @stage.save_list(list_all)
      @artist = Artist.find_or_create_by(name: stage_params[:name])
      @stage.artists << @artist
      flash[:success] = "新しいstageが登録されました"
      redirect_to @stage
    else
      render 'stages/new'
    end
  end

  def edit
    @stage = Stage.find(params[:id])
    @tag_list = @stage.tags.pluck(:tag_name).join(',')
    @list_all = @stage.lists.pluck(:tag_name).join(',')
  end

  def update
    @stage = Stage.find(params[:id])
    tag_list = params[:stage][:tag_name].split(',')
    list_all = params[:stage][:list_name].split(',')
    if @stage.update_attributes(stage_params)
      @stage.save_tag(tag_list)
      @stage.save_list(list_all)
      flash[:success] = "更新されました"
      redirect_to @stage
    end
  end

  def destroy
    @stage = Stage.find(params[:id])
    if @stage.destroy
      flash[:success] = "削除されました"
      redirect_to root_url
    else
      flash[:danger] = "管理人しか削除できません"
      redirect_to @stage
    end
  end

  private

    def stage_params
      params.require(:stage).permit(:name, :info, :from_date, :until_date, :place, images: [])
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_stage_form.html.erb
<%= form_with model: @stage, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class = 'form-group'>
    <%= f.label :name %>  <span class="input-need">※must</span>
    <%= f.text_field :name, class: 'form-control', id: 'stage_name' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :info %>
    <%= f.text_field :info, size: "60x4", class: 'form-control', id: 'stage_info' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :artists %>
    <%= f.text_field :artists, class: 'form-control', id: 'stage_artists' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :from_date %>
    <%= f.date_select :from_date, class: 'form-control', id: 'from_date' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :until_date %>
    <%= f.date_select :until_date, class: 'form-control', id: 'until_date' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control', id: 'place' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :images %>
    <%= f.file_field :images, multiple: true, class: 'form-control', id: 'images' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :tag %>
    <%= f.text_field :tag_name,
                     placeholder: "タグを複数つけるには' , 'で区切ってください", 
                     class: 'form-control' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :list %>
    <%= f.text_field :list_name,
                     placeholder: "複数のリストに入れるには' , 'で区切ってください", 
                     class: 'form-control' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/stages/_stage_images.html.erb
<div class="col-7">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% stage.images.each.with_index(0) do |image, index| %>
        <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= index.zero? ? 'active' : '' %>"></li>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <% stage.images.each_with_index do |image, index| %>
        <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
          <%= image_tag image, class: "sized d-block w-100" %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/stages/edit.html.erb
<% provide(:title, "Edit_stage") %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
     <%= form_with model: @stage, local: true do |f| %>
       <%= render 'shared/error_messages', object: f.object %>
       <div class = 'form-group'>
         <%= f.label :name %>　<span class="input-need">※must</span>
         <%= f.text_field :name, class: 'form-control', id: 'stage_name' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :info %>
         <%= f.text_field :info, size: "60x4", class: 'form-control', id: 'stage_info' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :from_date %>
         <%= f.date_select :from_date, class: 'form-control', id: 'from_date' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :until_date %>
         <%= f.date_select :until_date, class: 'form-control', id: 'until_date' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :place %>
         <%= f.text_field :place, class: 'form-control', id: 'place' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :images %>
         <%= f.file_field :images, multiple: true, class: 'form-control', id: 'images' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :tag %>
         <%= f.text_field :tag_name,
                          value: @tag_list,
                          placeholder: "タグを複数つけるには' , 'で区切ってください", 
                          class: 'form-control' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :list %>
         <%= f.text_field :list_name,
                          value: @list_all,
                          placeholder: "複数のリストに入れるには' , 'で区切ってください", 
                          class: 'form-control' %>
       </div>
       <%= f.submit "更新する", class: 'btn btn-primary' %>
       <%= link_to "削除する", stage_path(@stage), method: :delete,
                               data: { confirm: "本当に削除してよろしいですか？" } %>
     <% end %>
    </div>
  </div>
</div>

app/views/stages/new.html.erb
<% provide(:title, "New_stage") %>
<div class="container">
  <h1>New_Stage</h1>
  <div class="row">
    <div class="col-md-12">
      <%= render 'stages/stage_form' %>
    </div>
  </div>
</div>

app/views/stages/search.html.erb
<%= render "/layouts/search" %>

app/views/stages/show.html.erb
<% provide(:title, "#{@stage.name}") %>
<% @comments = @stage.feed_comment(@stage.id) %>
<div class="container">
  <div class="row">
    <% if @stage.images.attached? %>
      <%= render "stage_images", stage: @stage %>
    <% end %>
    <div class="col-5 contents-info">
      <h2 class="contents-name"><%= @stage.name %></h2>
      <h4><%= @stage.info %></h4>
      <div class="contents-date">
        <h5>公演日程：<%= @stage.from_date %>　〜　<%= @stage.until_date %></h5>
      </div>
    </div>
    <div class="col-12 edit-button">
      <div class="change-stage">
        <% if logged_in? %>
          <%= link_to "編集", edit_stage_path(@stage) %>　
        <% end %>
      </div>
      <p>
        #Tag:
        <% @stage_tags.each do |tag| %>
          <%= link_to tag.tag_name, tag_stages_path(tag_id: tag.id) %>
        <% end %>
      </p>
      <p>
        #List: 
        <% @stage_lists.each do |list| %>
          <%= link_to list.list_name, "../lists/#{list.id}" %>
        <% end %>
      </p>
    </div>
    <div class="col-12 comment">
      <%= render "comments/feed_comments" %>
      <%= render "comments/new" %>
    </div>
    <div class="relate_contents">
      <% @stage_tags.each do |stage_tag| %>
        <% stage_tag.stages.each do |relate_stage| %>
          <% unless relate_stage === @stage %>
              <% if relate_stage.images.attached? %>
            <div class="relate_image">
              <%= link_to image_tag(relate_stage.images.first, class: "stage_contents_image "), relate_stage %>
              <%= link_to relate_stage.name, relate_stage, class: "result_name" %>
            </div>
              <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/stages/tag.html.erb
<% provide(:title, "search") %>
<div class="container">
  <p>
    <%= "タグが - #{@tag.tag_name} - のstage一覧" %>
  </p>
  <div class="row search_result">
      <% @stages.each do |stage| %>
      <div class="search_image">
        <%= link_to image_tag("http://img.youtube.com/vi/#{stage.youtube_url}/hqdefault.jpg", class: "contents_image"), stage %>
        <%= link_to stage.name, stage, class: "result_name" %>
      </div>
      <% end %>
  </div>
</div>