config/routes.rb
Rails.application.routes.draw do
  root 'top_pages#top'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'

  resources :musics do
    collection do
      get 'search'
    end    
  end
  
  resources :dances do
    collection do
      get 'search'
    end
  end
  
  resources :stages do
    collection do
      get 'search'
    end      
  end
  
  resources :artists
  
  resources :tags do
    get 'musics',    to: 'musics#tag'
    get 'dances',    to: 'dances#tag'
    get 'stages',    to: 'stages#tag'
  end
  
  resources :lists do
    get 'musics',    to: 'musics#list'
    get 'dances',    to: 'dances#list'
    get 'stages',    to: 'stages#list'
  end

  resources :comments, only: [:create, :destroy]
end

app/models/music.rb
class Music < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true, length: { maximum: 50 }
  validates :info, length: { maximum: 200 }
  validates :youtube_url, presence: true
  before_save :shape_off
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :list_maps, dependent: :destroy
  has_many :lists, through: :list_maps
  has_many :comments, dependent: :destroy

  def shape_off
    self.youtube_url = youtube_url.last(11)
  end

  def feed_comment(music_id)
    Comment.where("music_id = ?", music_id)
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :logged_in_user, except: [:show, :tag, :list, :search]

  def new
    @music = Music.new
  end

  def show
    @music = Music.find(params[:id])
    @music_tags = @music.tags
    @music_lists = @music.lists
    @comment = Comment.new
  end

  def search
    @results = @q_music.result
  end

  def tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @musics = @tag.musics.all
  end

  def list
    @list_all = List.all
    @list = List.find(params[:list_id])
    @musics = @list.musics.all
  end

  def create
    @music = Music.new(music_params)
    tag_list = params[:music][:tag_name].split(',')
    list_all = params[:music][:list_name].split(',')
    if @music.save
      @music.save_tag(tag_list)
      @music.save_list(list_all)
      flash[:success] = "新しいmusicが登録されました"
      redirect_to @music
    else
      render 'musics/new'
    end
  end

  def edit
    @music = Music.find(params[:id])
    @tag_list = @music.tags.pluck(:tag_name).join(',')
    @list_all = @music.lists.pluck(:list_name).join(',')
  end

  def update
    @music = Music.find(params[:id])
    tag_list = params[:music][:tag_name].split(',')
    list_all = params[:music][:list_name].split(',')
    if @music.update_attributes(music_params)
      @music.save_tag(tag_list)
      @music.save_list(list_all)
      flash[:success] = "更新されました"
      redirect_to @music
    end
  end

  def destroy
    @music = Music.find(params[:id])
    if logged_in?
      @music.destroy
      flash[:success] = "削除されました"
      redirect_to root_url
    else
      flash[:danger] = "管理人しか削除できません"
      redirect_to @music
    end
  end

  private

    def music_params
      params.require(:music).permit(:name, :info, :date, :youtube_url)
    end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_music_form.html.erb
<%= form_with model: @music, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class = 'form-group'>
    <%= f.label :name %>  <span class="input-need">※must</span>
    <%= f.text_field :name, class: 'form-control', id: 'music_name' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :info %>
    <%= f.text_field :info, size: "60x4", class: 'form-control', id: 'music_info' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :date %>
    <%= f.date_select :date, class: 'form-control', id: 'music_date' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :youtube_url %>  <span class="input-need">※must</span>
    <%= f.text_field :youtube_url, class: 'form-control', id: 'music_youtube_url' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :tag %>
    <%= f.text_field :tag_name,
                     placeholder: "タグを複数つけるには' , 'で区切ってください", 
                     class: 'form-control' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :list %>
    <%= f.text_field :list_name,
                     placeholder: "複数のリストに入れるには' , 'で区切ってください", 
                     class: 'form-control' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/musics/edit.html.erb
<% provide(:title, "Edit_music") %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
     <%= form_with model: @music, local: true do |f| %>
       <%= render 'shared/error_messages', object: f.object %>
       <div class = 'form-group'>
         <%= f.label :name %>　<span class="input-need">※must</span>
         <%= f.text_field :name, class: 'form-control', id: 'music_name' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :info %>
         <%= f.text_field :info, size: "60x4", class: 'form-control', id: 'music_info' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :date %>
         <%= f.date_select :date, class: 'form-control', id: 'music_date' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :youtube_url %>  <span class="input-need">※must</span>
         <%= f.text_field :youtube_url, class: 'form-control', id: 'music_youtube_url' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :tag %>
         <%= f.text_field :tag_name,
                          value: @tag_list,
                          placeholder: "タグを複数つけるには' , 'で区切ってください", 
                          class: 'form-control' %>
       </div>
       <div class = 'form-group'>
         <%= f.label :list %>
         <%= f.text_field :list_name,
                          value: @list_all,
                          placeholder: "複数のリストに入れるには' , 'で区切ってください", 
                          class: 'form-control' %>
       </div>
       <%= f.submit "更新する", class: 'btn btn-primary' %>
       <%= link_to "削除する", music_path(@music), method: :delete,
                               data: { confirm: "本当に削除してよろしいですか？" } %>
     <% end %>
    </div>
  </div>
</div>

app/views/musics/new.html.erb
<% provide(:title, "New_music") %>
<div class="container">
  <h1>New_Music</h1>
  <div class="row">
    <div class="col-md-12">
      <%= render 'musics/music_form' %>
    </div>
  </div>
</div>

app/views/musics/search.html.erb
<%= render "/layouts/search" %>

app/views/musics/show.html.erb
<% provide(:title, "#{@music.name}") %>
<% @comments = @music.feed_comment(@music.id) %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <iframe width="100%" height="500px" src="https://www.youtube.com/embed/<%= @music.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="col-12 edit-button">
      <div class="change-music">
        <% if logged_in? %>
          <%= link_to "編集", edit_music_path(@music) %>　
        <% end %>
      </div>
    </div>
    <div class="col-12 contents-info">
      <h2 class="contents-name"><%= @music.name %></h2>
      <h4><%= @music.info %></h4>
      <div class="contents-date">
        <h5>リリース：<%= @music.date %></h5>
      </div>
      <p>
        #Tag:
        <% @music_tags.each do |tag| %>
          <%= link_to tag.tag_name, tag_musics_path(tag_id: tag.id) %>
        <% end %>
      </p>
      <p>
        #List: 
        <% @music_lists.each do |list| %>
          <%= link_to list.list_name, "../lists/#{list.id}" %>
        <% end %>
      </p>
    </div>
    <div class="col-12 comment">
      <%= render "comments/feed_comments" %>
      <%= render "comments/new" %>
    </div>
    <div class="relate_contents">
      <% @music_tags.each do |music_tag| %>
        <% music_tag.musics.each do |relate_music| %>
          <% unless relate_music === @music %>
            <div class="relate_image">
              <%= link_to image_tag("http://img.youtube.com/vi/#{relate_music.youtube_url}/mqdefault.jpg", class: "contents_image"), relate_music %>
              <%= link_to relate_music.name, relate_music, class: "result_name" %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/musics/tag.html.erb
<% provide(:title, "search") %>
<div class="container">
  <p>
    <%= "タグが - #{@tag.tag_name} - のmusic一覧" %>
  </p>
  <div class="row search_result">
      <% @musics.each do |music| %>
      <div class="search_image">
        <%= link_to image_tag("http://img.youtube.com/vi/#{music.youtube_url}/hqdefault.jpg", class: "contents_image"), music %>
        <%= link_to music.name, music, class: "result_name" %>
      </div>
      <% end %>
  </div>
</div>