config/routes.rb
Rails.application.routes.draw do
  root 'top_pages#top'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'

  resources :musics do
    collection do
      get 'search'
    end    
  end
  
  resources :dances do
    collection do
      get 'search'
    end
  end
  
  resources :stages do
    collection do
      get 'search'
    end      
  end
  
  resources :artists
  
  resources :tags do
    get 'musics',    to: 'musics#tag'
    get 'dances',    to: 'dances#tag'
    get 'stages',    to: 'stages#tag'
  end
  
  resources :lists do
    get 'musics',    to: 'musics#list'
    get 'dances',    to: 'dances#list'
    get 'stages',    to: 'stages#list'
  end

  resources :comments, only: [:create, :destroy]
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :info, length: { maximum: 200 }
  has_many_attached :images
  has_many :stage_artists, dependent: :destroy
  has_many :stage, through: :stage_artists
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :list_maps, dependent: :destroy
  has_many :lists, through: :list_maps
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :dance, optional: true
  belongs_to :music, optional: true
  belongs_to :stage, optional: true
  validates :content, presence: true, length: { maximum: 100 }
end

app/models/dance.rb
class Dance < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true, length: { maximum: 100 }
  validates :info, length: { maximum: 200 }
  validates :youtube_url, presence: true
  before_save :shape_off
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :list_maps, dependent: :destroy
  has_many :lists, through: :list_maps
  has_many :comments, dependent: :destroy

  def shape_off
    self.youtube_url = youtube_url.last(11)
  end

  def feed_comment(dance_id)
    Comment.where("dance_id = ?", dance_id)
  end
end

app/models/list.rb
class List < ApplicationRecord
  validates :list_name, presence: true, length: { maximum: 20 }
  has_many  :list_maps, dependent: :destroy, foreign_key: 'list_id'
  has_many  :dances, through: :list_maps
  has_many  :musics, through: :list_maps
  has_many  :stages, through: :list_maps
end

app/models/list_map.rb
class ListMap < ApplicationRecord
  belongs_to :dance, optional: true
  belongs_to :music, optional: true
  belongs_to :stage, optional: true
  belongs_to :list
  validates :list_id,presence:true
end

app/models/music.rb
class Music < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true, length: { maximum: 50 }
  validates :info, length: { maximum: 200 }
  validates :youtube_url, presence: true
  before_save :shape_off
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :list_maps, dependent: :destroy
  has_many :lists, through: :list_maps
  has_many :comments, dependent: :destroy

  def shape_off
    self.youtube_url = youtube_url.last(11)
  end

  def feed_comment(music_id)
    Comment.where("music_id = ?", music_id)
  end
end

app/models/stage.rb
class Stage < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :info, length: { maximum: 500 }
  has_many_attached :images
  has_many :stage_artists, dependent: :destroy
  has_many :artists, through: :stage_artists
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :list_maps, dependent: :destroy
  has_many :lists, through: :list_maps
  has_many :comments, dependent: :destroy

  def feed_comment(stage_id)
    Comment.where("stage_id = ?", stage_id)
  end
end

app/models/stage_artist.rb
class StageArtist < ApplicationRecord
  belongs_to :stage
  belongs_to :artist
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :tag_name, presence: true, length: { maximum: 20 }
  has_many  :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many  :dances, through: :tag_maps
  has_many  :musics, through: :tag_maps
  has_many  :stages, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :dance, optional: true
  belongs_to :music, optional: true
  belongs_to :stage, optional: true
  belongs_to :tag
  validates :tag_id,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  validates :name, presence: true, length: { maximum: 50 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dances_helper.rb
module DancesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <div class="row">
      <nav class="navbar navbar-light bg-light fixed-top">
<!-- Top -->
        <div class="col-2">
          <%= link_to "top", root_url, class: "navbar-brand" %>
        </div>
<!-- 検索バー -->
        <div class="search_bar navbar-nav col-9">
          <div class="row">
              <div class="col-2 select_box">
                <%= select_tag(:select_box, options_for_select([['Dances', 1], ['Musics', 2], ['Stages', 3]]), {:onchange => "change();"}) %>
              </div>
              <div class="search_form col-9" id="search_dance">
                <%= search_form_for @q_dance, url: search_dances_path do |f| %>
                  <div class="row">
                    <div class="col-10">
                      <%= f.search_field :name_cont, 
                                         placeholder: "all",
                                         class: "form-control" %>
                    </div>
                    <div class="search_submit col-2">
                      <%= f.submit '検索', class: "btn" %>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="search_form col-9" id="search_music" style="display: none;">
                <%= search_form_for @q_music, url: search_musics_path do |f| %>
                  <div class="row">
                    <div class="col-10">
                      <%= f.search_field :name_cont, 
                                         placeholder: "all",
                                         class: "form-control" %>
                    </div>
                    <div class="search_submit col-2">
                      <%= f.submit '検索', class: "btn" %>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="search_form col-9" id="search_stage" style="display: none;">
                <%= search_form_for @q_stage, url: search_stages_path do |f| %>
                  <div class="row">
                    <div class="col-10">
                      <%= f.search_field :name_cont, 
                                         placeholder: "all",
                                         class: "form-control" %>
                    </div>
                    <div class="search_submit col-2">
                      <%= f.submit '検索', class: "btn" %>
                    </div>
                  </div>
                <% end %>
              </div>
          </div>
        </div>
<!-- ハンバーガーボタン -->
        <div class="hamburger col-1">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <% if logged_in? %>
                  <li class="nav-item">
                    <%= link_to 'new_music', '/musics/new', class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'new_dance', '/dances/new', class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'new_stage', '/stages/new', class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'new_artist', '/artists/new', class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'ログアウト', logout_path, method: :delete, class: "nav-link" %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to 'ログイン', login_path, class: "nav-link" %>
                  </li>
                <% end %>
                  <li class="nav-item">
                    <%= link_to '再生リスト', '/lists/', class: "nav-link" %>
                  </li>
              </ul>
            </div>
        </div>
        </div>
      </div>
    </nav>
  </div>
 </div>
</header>

<script>
function change() {
  if (document.getElementById("select_box")) {
    select_boxValue = document.getElementById("select_box").value;
    if (select_boxValue == "1") {
      document.getElementById("search_dance").style.display = "";
      document.getElementById("search_music").style.display = "none";
      document.getElementById("search_stage").style.display = "none";
    } else if (select_boxValue == "2") {
      document.getElementById("search_dance").style.display = "none";
      document.getElementById("search_music").style.display = "";
      document.getElementById("search_stage").style.display = "none";
    } else if (select_boxValue == "3") {
      document.getElementById("search_dance").style.display = "none";
      document.getElementById("search_music").style.display = "none";
      document.getElementById("search_stage").style.display = "";
    }
  }
}
</script>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_pack_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_search.html.erb
<% provide(:title, "search") %>
<div class="container">
  <div class="row search_result">
    <% @results.each do |result| %>
      <div class="search_image">
        <%= link_to image_tag("http://img.youtube.com/vi/#{result.youtube_url}/hqdefault.jpg", class: "contents_image"), "#{result.id}" %>
        <%= link_to result.name, "#{result.id}", class: "result_name" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="page">
      <%= render 'layouts/header' %> 
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%#= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>